### PR TITLE
 Reorganized files according to the guideline

### PR DESCRIPTION
**Pull request by number000000**

### CODE REVIEW

**Comment by kungharrison** [comment]
@number000000 I think we should change it so all the html files should be in their own file (i.e. /assets/html) to reduce clutter in the main directory

**Review by kungharrison — CHANGES_REQUESTED** [review]
I think we need to move all html files to separate assets folder otherwise it will clutter up the main directory too much

**Comment by number000000** [comment]
Make sense. I put them in assets/html.
I'll update the wiki page accordingly

**Review by kungharrison — APPROVED** [review]
Looks good now!

**Pull request merged**
