### PR TITLE
HTML + CSS For Issue #9

### PR DESCRIPTION
**Pull request by AmnesiacSloth**
The file directory has been also been restructured inline with the Github wiki guidelines. Let me know if this looks solid 👍🏼

### CODE REVIEW

**Comment by AmnesiacSloth** [comment]
Looks like I might need to fix a ton of styling errors? Not sure what else I need to do to pass the checks.

**Comment by kungharrison** [comment]
@AmnesiacSloth Don't worry about it too much for now, the linter is pretty strict, so Holden is going to work on that.

**Comment by AmnesiacSloth** [comment]
Should I be fixing the style or leave as is for now? I might be able to clean up the code but I wanted to push asap so the rest of the team has a template to work on the javascript

**Comment by kungharrison** [comment]
@AmnesiacSloth You can leave the styling for now but once @HoldenA1 finishes reducing the linter strictness on the Kanban everyone should be following it.

**Review by kungharrison — APPROVED** [review]
Looks good so far!

**Pull request merged**
